### ISSUE TITLE
support for BTS/videos

### ISSUE THREAD

**Issue by Vexcited** [Vexcited/StayReal#11]
as described in #6 

- [x] find API property
- [x] implement to view

**Comment by Vexcited** [comment]
done in https://github.com/Vexcited/StayReal/commit/17ff0da07c245955af6317bc11d3a603f0cf857a

**Comment by GWPvGWP** [comment]
Is this only BTS or also the new video feature?

**Comment by Vexcited** [comment]
> Is this only BTS or also the new video feature?

What is the "new video" feature ? I haven't see it at all in my country ? I only know about BTS...

**Comment by GWPvGWP** [comment]
I start doubting myself now...
I'm pretty sure I have seen it, but I need to check tonight since I barely use the official app.

See it mentioned here: https://www.reddit.com/r/bereal_app/comments/1g3t2yt/bereal_videos/
Somehow not everyone seems to have it.

**Comment by Vexcited** [comment]
I see... well whenever I'll have them enabled, I'll open a new issue and probably implement them.

**Comment by GWPvGWP** [comment]
Well nvm for now. I couldn't find anyone using it in my feed. So it might be abandoned already or just nobody uses it. I also thought they quitted the bts, but seemingly that is back, though few people seem to use it.
